language: node_js

node_js:
  - "node"

cache:
  directories:
  - "$HOME/.npm"

matrix:
  include:
    - env: TAILWINDCSS_VERSION=latest
    - env: TAILWINDCSS_VERSION=
    - env: TAILWINDCSS_VERSION=~1.4
    - env: TAILWINDCSS_VERSION=~1.3
    - env: TAILWINDCSS_VERSION=~1.2
  allow_failures:
    - env: TAILWINDCSS_VERSION=@latest

before_script:
  - if [[ $TAILWINDCSS_VERSION ]]; then
      npm install tailwindcss@$TAILWINDCSS_VERSION;
    fi
